from enum import Enum
class MemorySize(Enum):
    BIT0        =   "M"
    BIT1        =   "N"
    BIT2        =   "O"
    BIT3        =   "P"
    BIT4        =   "Q"
    BIT5        =   "R"
    BIT6        =   "S"
    BIT7        =   "T"
    BIT8        =   "H"
    BIT16       =   " "
    BIT24       =   "W"
    BIT32       =   "X"
    BIT16_RE    =   "I"
    BIT24_RE    =   "J"
    BIT32_RE    =   "G"
    LOWER4      =   "L"
    UPPER4      =   "U"
    BITCOUNT    =   "K"
    FLOAT       =   "fF"
    FLOAT_BE    =   "fB"
    DOUBLE32    =   "fH"
    DOUBLE32_BE =   "fI"
    MBF32       =   "fM"
    MBF32_LE    =   "fL"

class MemoryType(Enum):
    MEM     = ""
    DELTA   = "d"
    PRIOR   = "p"
    BCD     = "b"
    INVERT  = "~"
    RECALL  = "{recall}"

class Flag(Enum):
    NONE              = ""
    PAUSE_IF          = "P:"
    RESET_IF          = "R:"
    RESET_NEXT_IF     = "Z:"
    ADD_HITS          = "C:"
    SUB_HITS          = "D:"
    ADD_SOURCE        = "A:"
    SUB_SOURCE        = "B:"
    ADD_ADDRESS       = "I:"
    MEASURED          = "M:"
    TRIGGER           = "T:"
    AND_NEXT          = "N:"
    OR_NEXT           = "O:"
    MEASURED_PERCENT  = "G:"
    MEASURED_IF       = "Q:"
    REMEMBER          = "K:"

class LeaderboardFormat(Enum):
    SCORE        =  "SCORE"
    TIME         =  "TIME"
    MILLISECS    =  "MILLISECS"
    FRAMES       =  "FRAMES"
    SECS         =  "SECS"
    MINUTES      =  "MINUTES"
    SECS_AS_MINS =  "SECS_AS_MINS"
    VALUE        =  "VALUE"
    FLOAT1       =  "FLOAT1"
    FLOAT2       =  "FLOAT2"
    FLOAT3       =  "FLOAT3"
    FLOAT4       =  "FLOAT4"
    FLOAT5       =  "FLOAT5"
    FLOAT6       =  "FLOAT6"