from enum import Enum
class MemorySize(Enum):
    BIT0        =   "M"
    BIT1        =   "N"   
    BIT2        =   "O"
    BIT3        =   "P"
    BIT4        =   "Q"
    BIT5        =   "R"
    BIT6        =   "S"
    BIT7        =   "T"
    BIT8        =   "H"
    BIT16       =   " "  
    BIT24       =   "W"
    BIT32       =   "X"
    BIT16_RE    =   "I"
    BIT24_RE    =   "J" 
    BIT32_RE    =   "G" 
    LOWER4      =   "L"
    UPPER4      =   "U"
    BITCOUNT    =   "K"  
    FLOAT       =   "fF"  
    FLOAT_BE    =   "fB"  
    MBF32       =   "fM"  
    MBF32_LE    =   "fL"  

class MemoryType(Enum):
    MEM     = ""
    DELTA   = "d"
    PRIOR   = "p"
    BCD     = "b"
    INVERT  = "~"

class Flag(Enum):
    NONE              = ""
    PAUSE_IF          = "P:"
    RESET_IF          = "R:"
    RESET_NEXT_IF     = "Z:"
    ADD_HITS          = "C:"
    SUB_HITS          = "B:"
    ADD_SOURCE        = "A:"
    SUB_SOURCE        = "B:"
    ADD_ADRESS        = "I:"
    MEASURED          = "M:"
    TRIGGER           = "T:"
    AND_NEXT          = "N:"
    OR_NETX           = "O:"
    MEASURED_PRECENT  = "G:"
    MEASURED_IF       = "Q:"
    REMEMBER          = "K:"
