import requests
import re
import os
import sys
import getpass


try:
    from config import USER, PASSWORD
except ImportError:
    USER = ""
    PASSWORD = ""

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

def sanitize_name(note_text):
    clean = re.sub(r'\[.*?\]|\(.*?\)', '', note_text)
    clean = re.sub(r'[^a-zA-Z0-9\s]', '', clean)
    clean = "_".join(clean.lower().split())
    if clean and clean[0].isdigit():
        clean = "var_" + clean
    return clean[:40]

def detect_type(note_text):
    lower = note_text.lower()
    if "32-bit" in lower or "32 bit" in lower or "32bit" in lower: return "dword"
    if "24-bit" in lower or "24 bit" in lower or "24bit" in lower: return "tbyte"
    if "16-bit" in lower or "16 bit" in lower or "16bit" in lower: return "word"
    if "float" in lower: return "float32"
    return "byte"

def main():
    print("--- Pycheevos Note Importer (Debug Mode) ---")

    user = USER if USER else input("RA Username: ").strip()
    if not user:
        user = input("RA Username: ").strip()

    password = PASSWORD if PASSWORD else getpass.getpass("RA Password: ").strip()
    if not password:
        password = getpass.getpass("RA Password: ").strip()

    game_id = input("Game ID: ").strip()

    if not user or not password or not game_id:
        print("Error: All fields are required.")
        return

    print(f"\n[LOG] dados recebidos -> User:{user} | ID:{game_id}\n")

    if not user or not password or not game_id:
        print("Error: All fields are required")
        return

    url = "https://retroachievements.org/dorequest.php"
    
    login_params = {
        'r': 'login',
        'u': user,
        'p': password
    }

    try:
        sess = requests.Session()
        sess .headers.update({'User-Agent': f'PyCheevos_Importer/1.0 ({user})'})
        resp_login = sess.post(url, data=login_params).json()

        if not resp_login.get('Success'):
            print(f"Falha no login: {resp_login.get('Error')}")

        token = resp_login.get('Token')
        print("[LOG]: Login realizado! Token obtido.\n")
    except Exception as e:
        print(f"Connection error: {e}")
        return
    
    print(f"[LOG] Baixando notas do jogo {game_id}...\n")
    
    notes_params = {
        'r': 'codenotes2',
        'g': game_id,
        'u': user,
        't': token
    }

    try:
        resp_notes = sess.post(url, data=notes_params).json()
        
        if not resp_notes.get('Success'):
            print(f"Erro ao baixar notas: {resp_notes.get('Error')}")
            print("Tentando método antigo...")
            notes_params['r'] = 'codenotes'
            resp_notes = sess.post(url, data=notes_params).json()
            if not resp_notes.get('Success'):
                return
        notes = resp_notes.get('CodeNotes', [])
        print(f"Success! {len(notes)} notes found. Generating file...\n")

    except Exception as e:
        print(f"Erro ao processar notas: {e}")

    lines = []
    lines.append(f"# Code notes for game ID {game_id}")
    lines.append(f"# Automatically generated by PyCheevos")
    lines.append("")
    lines.append("from core.helpers import byte, word, tbyte, dword, float32")
    lines.append("")

    count = 0
    used_names = {}

    for note in notes: # type: ignore
        addr = note["Address"]
        raw_note = note.get("Note", "")
        
        if not raw_note: continue

        mem_type = detect_type(raw_note)
        var_name = sanitize_name(raw_note)

        if not var_name: var_name = f"unk_{addr}"
        
        if var_name in used_names:
            used_names[var_name] += 1
            var_name = f"{var_name}_{used_names[var_name]}"
        else:
            used_names[var_name] = 1

        clean_comment = raw_note.replace('\n', ' ').replace('\r', '')
        
        lines.append(f"# {addr}: {clean_comment}")
        lines.append(f"{var_name} = {mem_type}({addr})")
        lines.append("")
        count += 1


    output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'scripts'))
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    filename = os.path.join(output_dir, f"notes_{game_id}.py")
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("-------------------------------------------")
    print(f"Success! File generated in: {filename}")
    print(f"Total number of addresses mapped: {count}")
    print("-------------------------------------------")

if __name__ == "__main__":
    main()